const sig = (label, type) => {
  const m = { intent: { bg: "#FAEEDA", color: "#854F0B" }, content: { bg: "#E6F1FB", color: "#185FA5" }, growth: { bg: "#E1F5EE", color: "#0F6E56" }, tech: { bg: "#EEEDFE", color: "#534AB7" }, risk: { bg: "#FCEBEB", color: "#A32D2D" }, momentum: { bg: "#E1F5EE", color: "#0F6E56" }, stakeholder: { bg: "#E6F1FB", color: "#185FA5" }, timing: { bg: "#FAEEDA", color: "#854F0B" }, competitive: { bg: "#EEEDFE", color: "#534AB7" }, coaching: { bg: "#FFF0E6", color: "#9C4D1A" } };
  return { label, ...(m[type] || m.intent) };
};

export const COMPANY_NAME = "CargoTuff";
export const COMPANY_LOGO_LETTER = "C";
export const ROLE_LABEL = "CRO";
export const REP = { name: "Marcus Webb", avatar: "MW" };

export const TABS = ["Revenue overview", "Team performance", "Forecast risk", "Strategic accounts"];

export const ALL_LEADS = {
  "Revenue overview": [
    { id: 1, name: "Derek Hanson", company: "Maersk Logistics NA", role: "VP Global Procurement", stage: "Negotiation", size: "$920K", score: 94, signals: [sig("RFP issued for dunnage airbags", "intent"), sig("3-year contract renewal window", "timing"), sig("Expanding intermodal routes", "growth")], message: "Maersk is consolidating load securement vendors across NA. They want a single-source agreement covering airbags, lashing, and strapping for all intermodal freight. Decision expected by mid-April.", priority: "high" },
    { id: 2, name: "Rachel Odom", company: "Union Pacific Railroad", role: "Director of Safety & Compliance", stage: "Proposal Sent", size: "$1.1M", score: 91, signals: [sig("New FRA safety mandate", "intent"), sig("Cargo damage claims up 18%", "risk"), sig("Budget approved Q2", "timing")], message: "Union Pacific needs to upgrade dunnage airbag specs across 14 rail yards to meet new Federal Railroad Administration guidelines. Budget is pre-approved and they're evaluating two finalists.", priority: "high" },
    { id: 3, name: "Tom Nguyen", company: "XPO Logistics", role: "Chief Procurement Officer", stage: "Discovery", size: "$680K", score: 82, signals: [sig("Visited strapping product pages 12x", "content"), sig("Opened pricing PDF", "intent"), sig("Acquired new LTL division", "growth")], message: "XPO's LTL expansion is driving demand for strapping and lashing systems. Tom requested a capabilities overview and wants to understand volume pricing for 50+ distribution centers.", priority: "medium" },
    { id: 4, name: "Angela Fischer", company: "CMA CGM America", role: "Head of Container Operations", stage: "Closed Won", size: "$750K", score: 98, signals: [sig("Contract signed", "momentum"), sig("Rollout to 8 ports", "growth"), sig("Referral to sister company", "stakeholder")], message: "CMA CGM signed a $750K annual contract for dunnage airbags and lashing systems. Rollout underway across Gulf and East Coast ports. Angela is introducing us to her counterpart at ANL Container Line.", priority: "high" },
    { id: 5, name: "James Kowalski", company: "Schneider National", role: "VP Fleet Operations", stage: "Qualification", size: "$430K", score: 74, signals: [sig("Attended webinar on cargo shifting", "content"), sig("Driver complaint reports increasing", "risk"), sig("Fleet expanding by 2,000 trailers", "growth")], message: "Schneider is adding trailers and seeing more cargo shift incidents. James attended our webinar and asked for a fleet-wide assessment of their current load securement practices.", priority: "medium" },
    { id: 6, name: "Patricia Morales", company: "BNSF Railway", role: "Senior Manager Intermodal", stage: "Negotiation", size: "$1.3M", score: 93, signals: [sig("Multi-year deal structure requested", "intent"), sig("Competitor pricing undercut", "competitive"), sig("Safety audit Q3", "timing")], message: "BNSF wants a 5-year framework agreement for all dunnage and lashing products. They received a lower bid from a competitor but have quality concerns. Our safety track record is the differentiator.", priority: "high" },
    { id: 7, name: "Kevin Zhao", company: "Kuehne+Nagel US", role: "Director Supply Chain Solutions", stage: "Proposal Sent", size: "$520K", score: 85, signals: [sig("Evaluating 3 vendors", "competitive"), sig("Q2 implementation target", "timing"), sig("Downloaded case study", "content")], message: "Kuehne+Nagel is standardizing load securement across their US contract logistics operations. Kevin wants a pilot program at their Memphis hub before committing to a national rollout.", priority: "medium" },
    { id: 8, name: "Sandra Ellis", company: "Hapag-Lloyd Americas", role: "VP Cargo Integrity", stage: "Discovery", size: "$880K", score: 79, signals: [sig("Cargo claims up 22% YoY", "risk"), sig("New sustainability requirements", "tech"), sig("Benchmarking competitors", "competitive")], message: "Hapag-Lloyd is reviewing all cargo securement vendors due to rising damage claims. Sandra is particularly interested in our recyclable dunnage airbag line and wants an environmental impact comparison.", priority: "medium" },
    { id: 9, name: "Brian Caldwell", company: "Old Dominion Freight Line", role: "National Accounts Manager", stage: "Closed Won", size: "$310K", score: 96, signals: [sig("Reorder placed", "momentum"), sig("Expanding to 5 new terminals", "growth"), sig("NPS score 9/10", "stakeholder")], message: "Old Dominion reordered strapping and lashing kits for terminal expansion. They've become a vocal reference customer and Brian has agreed to participate in our next case study.", priority: "low" },
    { id: 10, name: "Lisa Tran", company: "Crowley Maritime", role: "Director Logistics Procurement", stage: "Qualification", size: "$590K", score: 71, signals: [sig("Jones Act compliance needs", "intent"), sig("Puerto Rico route expansion", "growth"), sig("Requested product samples", "content")], message: "Crowley is expanding Caribbean routes and needs Jones Act-compliant load securement for domestic ocean shipping. Lisa requested samples of our marine-grade dunnage airbags for testing.", priority: "medium" }
  ],
  "Team performance": [
    { id: 11, name: "Sarah Mitchell", company: "Werner Enterprises", role: "Procurement Lead", stage: "Discovery", size: "$340K", score: 68, signals: [sig("Rep response time slow", "coaching"), sig("Demo scheduled", "momentum"), sig("Budget cycle starts May", "timing")], message: "Werner is interested in upgrading from generic airbags to our heavy-duty line. Sarah's rep has been slow to follow up and we risk losing momentum before their May budget cycle.", priority: "medium" },
    { id: 12, name: "Alan Drexler", company: "J.B. Hunt Transport", role: "VP Intermodal Operations", stage: "Negotiation", size: "$760K", score: 88, signals: [sig("Champion identified", "stakeholder"), sig("Intermodal volume up 30%", "growth"), sig("Competitor contract expiring", "competitive")], message: "J.B. Hunt's current load securement vendor contract expires in June. Alan is our champion and pushing for CargoTuff. The assigned rep is managing this well but needs executive alignment support.", priority: "high" },
    { id: 13, name: "Megan Farrell", company: "Ryder System", role: "Supply Chain Director", stage: "Proposal Sent", size: "$480K", score: 81, signals: [sig("Proposal viewed 6x", "intent"), sig("Asked about lead times", "timing"), sig("Multi-location rollout", "growth")], message: "Ryder reviewed our proposal multiple times and is asking about lead times for a 40-location rollout. Rep needs to close this before end of Q2 to hit quota.", priority: "high" },
    { id: 14, name: "Carlos Reyes", company: "Echo Global Logistics", role: "Head of Carrier Relations", stage: "Discovery", size: "$220K", score: 63, signals: [sig("Inbound lead from trade show", "intent"), sig("Small initial order likely", "risk"), sig("3PL growth segment", "growth")], message: "Echo came in from the MODEX trade show. Carlos wants to offer CargoTuff products to their carrier network. Start small but could scale significantly if we prove ROI.", priority: "low" },
    { id: 15, name: "Janet Woodward", company: "Norfolk Southern", role: "Manager Rail Cargo Safety", stage: "Qualification", size: "$650K", score: 76, signals: [sig("Safety incident triggered review", "risk"), sig("Board-level visibility", "stakeholder"), sig("Fast-track procurement", "timing")], message: "A recent derailment-related cargo incident has Norfolk Southern fast-tracking their load securement vendor review. Janet reports directly to their SVP of Safety. High urgency.", priority: "high" },
    { id: 16, name: "David Park", company: "FedEx Freight", role: "Director Terminal Operations", stage: "Proposal Sent", size: "$550K", score: 84, signals: [sig("Pilot program approved", "momentum"), sig("3 terminals selected", "growth"), sig("Decision by April 15", "timing")], message: "FedEx Freight approved a pilot at three high-volume terminals. David needs final pricing by April 15 for his internal business case. Rep is handling well.", priority: "high" },
    { id: 17, name: "Brittany Lane", company: "Saia Inc.", role: "Procurement Specialist", stage: "Discovery", size: "$190K", score: 59, signals: [sig("Downloaded product catalog", "content"), sig("First touch", "momentum"), sig("Regional carrier", "growth")], message: "Saia is a growing regional LTL carrier exploring load securement upgrades. Early-stage lead but Brittany is engaged and responsive. Good coaching opportunity for junior rep.", priority: "low" },
    { id: 18, name: "Robert Tate", company: "Dole Food Company", role: "VP Global Shipping", stage: "Negotiation", size: "$410K", score: 87, signals: [sig("Temperature-sensitive cargo needs", "tech"), sig("Reefer container focus", "intent"), sig("Global contract potential", "growth")], message: "Dole needs specialized dunnage for refrigerated containers shipping produce. Robert wants a global framework but is starting with US-to-Latin America routes. High expansion potential.", priority: "high" },
    { id: 19, name: "Heather Grant", company: "ArcBest Corporation", role: "National Account Manager", stage: "Closed Won", size: "$280K", score: 95, signals: [sig("Contract renewed", "momentum"), sig("Added strapping line", "growth"), sig("Rep exceeded quota", "coaching")], message: "ArcBest renewed and expanded their contract to include our full strapping product line. This was a clean close by our top-performing rep. Good example for team coaching sessions.", priority: "low" },
    { id: 20, name: "Victor Salinas", company: "Matson Navigation", role: "Director Pacific Operations", stage: "Qualification", size: "$370K", score: 72, signals: [sig("Pacific route cargo damage", "risk"), sig("Hawaii/Alaska compliance", "intent"), sig("Seasonal volume spike Q3", "timing")], message: "Matson is experiencing increased cargo damage on Pacific routes and needs marine-rated lashing systems. Q3 is their peak season so timing is critical for a summer deployment.", priority: "medium" }
  ],
  "Forecast risk": [
    { id: 21, name: "Greg Holloway", company: "CSX Transportation", role: "VP Procurement", stage: "Stalled", size: "$980K", score: 65, signals: [sig("No response in 3 weeks", "risk"), sig("Budget freeze rumored", "risk"), sig("Champion left company", "stakeholder")], message: "CSX deal has gone cold after our champion Greg's direct report left the company. Rumors of a broader procurement freeze. This is $980K at risk in our Q2 forecast and needs executive intervention.", priority: "high" },
    { id: 22, name: "Diana Ross-Park", company: "Evergreen Marine Corp", role: "Head of NA Operations", stage: "Negotiation", size: "$720K", score: 70, signals: [sig("Legal review delays", "risk"), sig("Competitor offering free trial", "competitive"), sig("Q2 deadline at risk", "timing")], message: "Evergreen's legal team is taking longer than expected on contract review. Meanwhile, a competitor is offering a 90-day free trial. We need to accelerate legal or this slips to Q3.", priority: "high" },
    { id: 23, name: "Mike Brennan", company: "Hub Group", role: "COO", stage: "Proposal Sent", size: "$450K", score: 58, signals: [sig("Proposal unopened for 10 days", "risk"), sig("Restructuring announced", "risk"), sig("Key contact reassigned", "stakeholder")], message: "Hub Group announced an internal restructuring and our key contact Mike has been reassigned. Proposal hasn't been opened. Need to identify new stakeholder immediately or remove from forecast.", priority: "high" },
    { id: 24, name: "Christine Yee", company: "Yang Ming Marine", role: "Regional Procurement Director", stage: "Discovery", size: "$560K", score: 55, signals: [sig("Delayed discovery call twice", "risk"), sig("Evaluating 5 vendors", "competitive"), sig("Long procurement cycle", "timing")], message: "Yang Ming has delayed our discovery call twice and is running a broad vendor evaluation. Their procurement cycles typically run 6+ months. Low confidence this closes in Q2.", priority: "medium" },
    { id: 25, name: "Paul Anderson", company: "Landstar System", role: "Director Agent Services", stage: "Qualification", size: "$310K", score: 52, signals: [sig("Agent model complicates decision", "risk"), sig("No single buyer", "stakeholder"), sig("Price sensitivity high", "competitive")], message: "Landstar's agent-based model means no centralized purchasing. Paul is trying to build consensus but each agent operates independently. Deal structure unclear and price sensitivity is high.", priority: "medium" },
    { id: 26, name: "Jennifer Walsh", company: "Hyundai Glovis", role: "Americas Logistics Manager", stage: "Stalled", size: "$840K", score: 48, signals: [sig("HQ approval required (Seoul)", "risk"), sig("Currency fluctuation concern", "risk"), sig("6-month decision timeline", "timing")], message: "Hyundai Glovis requires Seoul HQ approval for all vendor contracts above $500K. Jennifer is supportive locally but has limited authority. Currency fluctuations are also making them hesitant on USD pricing.", priority: "high" },
    { id: 27, name: "Steve O'Brien", company: "Knight-Swift Transportation", role: "VP Supply Chain", stage: "Negotiation", size: "$670K", score: 73, signals: [sig("Asking for 25% discount", "competitive"), sig("Incumbent vendor matching price", "competitive"), sig("Decision pushed to May", "timing")], message: "Knight-Swift is using our proposal to negotiate with their incumbent. Steve asked for a 25% discount which would put us below margin threshold. Need value-based repositioning.", priority: "high" },
    { id: 28, name: "Laura Kim", company: "ZIM Integrated Shipping", role: "Procurement Manager", stage: "Discovery", size: "$390K", score: 61, signals: [sig("Interested but no budget owner", "risk"), sig("Pilot requested but unfunded", "stakeholder"), sig("Tariff uncertainty", "risk")], message: "ZIM wants to pilot our products on Asia-US routes but Laura hasn't identified a budget owner. Tariff uncertainty is making leadership hesitant to commit to new vendor relationships.", priority: "medium" },
    { id: 29, name: "Anthony Russo", company: "Heartland Express", role: "Fleet Safety Director", stage: "Proposal Sent", size: "$280K", score: 66, signals: [sig("Insurance carrier pushing upgrade", "intent"), sig("CFO approval needed", "stakeholder"), sig("Q2 budget uncertain", "risk")], message: "Heartland's insurance carrier recommended upgrading load securement but the CFO hasn't approved the spend. Anthony is motivated but doesn't control the budget. Medium risk to Q2.", priority: "medium" },
    { id: 30, name: "Nicole Pham", company: "Wan Hai Lines", role: "Director NA Trade Lane", stage: "Stalled", size: "$510K", score: 44, signals: [sig("Went silent after pricing", "risk"), sig("Internal reorganization", "risk"), sig("Competitor won pilot", "competitive")], message: "Wan Hai went silent after receiving our pricing. Intel suggests a competitor won their initial pilot. Combined with internal reorg, this deal should likely be moved to Q3 or removed from pipeline.", priority: "high" }
  ],
  "Strategic accounts": [
    { id: 31, name: "William Chen", company: "Amazon Global Logistics", role: "Head of Freight Procurement", stage: "Negotiation", size: "$2.1M", score: 92, signals: [sig("Enterprise RFP in progress", "intent"), sig("Multi-modal requirement", "growth"), sig("Sustainability mandate", "tech")], message: "Amazon is consolidating load securement across their freight network. They need dunnage, lashing, and strapping for truck, rail, ocean, and air. Sustainability certifications are a hard requirement.", priority: "high" },
    { id: 32, name: "Rebecca Torres", company: "Walmart Transportation", role: "Senior Director Private Fleet", stage: "Proposal Sent", size: "$1.6M", score: 88, signals: [sig("Private fleet expansion", "growth"), sig("Safety scorecard improvement goal", "intent"), sig("Incumbent underperforming", "competitive")], message: "Walmart's private fleet is expanding and their current vendor is failing quality audits. Rebecca needs a supplier who can scale to 150+ distribution centers with consistent quality.", priority: "high" },
    { id: 33, name: "Daniel Kim", company: "Target Corporation", role: "VP Supply Chain Operations", stage: "Discovery", size: "$890K", score: 78, signals: [sig("Inbound freight optimization project", "intent"), sig("Carrier compliance program", "stakeholder"), sig("Q3 implementation window", "timing")], message: "Target is overhauling their inbound freight program and wants to mandate load securement standards for all carriers. Daniel is exploring whether to provide products directly or set specifications.", priority: "high" },
    { id: 34, name: "Maria Gutierrez", company: "Home Depot Supply Chain", role: "Director DC Operations", stage: "Qualification", size: "$720K", score: 75, signals: [sig("DC network expansion", "growth"), sig("Vendor consolidation initiative", "intent"), sig("Product damage reduction KPI", "risk")], message: "Home Depot is opening 3 new distribution centers and wants to consolidate from 4 load securement vendors to 1. Maria's team is benchmarking product damage rates across current suppliers.", priority: "medium" },
    { id: 35, name: "Andrew Phillips", company: "Costco Logistics", role: "VP Depot Operations", stage: "Closed Won", size: "$940K", score: 97, signals: [sig("3-year agreement signed", "momentum"), sig("Expanding to all 12 depots", "growth"), sig("Executive sponsor secured", "stakeholder")], message: "Costco signed a 3-year strategic agreement covering all depot operations. Andrew has been a strong executive sponsor and is open to co-developing custom dunnage solutions for oversized items.", priority: "low" },
    { id: 36, name: "Susan Park", company: "Procter & Gamble", role: "Global Transportation Manager", stage: "Negotiation", size: "$1.4M", score: 86, signals: [sig("Global framework interest", "growth"), sig("Sustainability scorecard weight", "tech"), sig("Current vendor contract ending", "timing")], message: "P&G wants a global framework agreement starting with North America. Their sustainability scorecard weighs heavily in vendor selection and our recyclable product line gives us an edge.", priority: "high" },
    { id: 37, name: "Ryan Cooper", company: "PepsiCo Beverages", role: "Head of Freight Operations", stage: "Proposal Sent", size: "$1.1M", score: 83, signals: [sig("Seasonal volume surge planning", "timing"), sig("Heavy load requirements", "tech"), sig("Multi-division opportunity", "growth")], message: "PepsiCo needs heavy-duty strapping and lashing for beverage shipments. Ryan manages freight across Pepsi, Frito-Lay, and Quaker. Initial proposal covers beverages with expansion potential.", priority: "high" },
    { id: 38, name: "Karen White", company: "Caterpillar Inc.", role: "Director Parts Logistics", stage: "Discovery", size: "$650K", score: 71, signals: [sig("Oversized parts securement challenge", "tech"), sig("Global dealer network", "growth"), sig("Engineering team involved", "stakeholder")], message: "Caterpillar needs custom load securement for oversized equipment parts shipped to their global dealer network. Engineering team wants to co-design solutions. Long cycle but high lifetime value.", priority: "medium" },
    { id: 39, name: "Thomas Brown", company: "John Deere", role: "VP Supply Chain", stage: "Qualification", size: "$780K", score: 74, signals: [sig("Agricultural equipment shipping", "tech"), sig("Seasonal demand alignment", "timing"), sig("Midwest distribution focus", "growth")], message: "Deere needs specialized securement for agricultural equipment and parts with heavy seasonal swings. Thomas wants a supplier who can flex capacity during spring planting and fall harvest seasons.", priority: "medium" },
    { id: 40, name: "Emily Nakamura", company: "Tesla Fremont Operations", role: "Logistics Program Manager", stage: "Discovery", size: "$560K", score: 69, signals: [sig("EV parts require custom solutions", "tech"), sig("Rapid scaling", "growth"), sig("Procurement process complex", "risk")], message: "Tesla needs custom dunnage for battery pack and EV component shipping. Emily is early in evaluation but Tesla's rapid scaling means this could grow quickly. Procurement process is multi-layered.", priority: "medium" }
  ]
};

export const CHAT_RESPONSES = {
  revenue_forecast: "Q2 revenue is tracking at $9.4M against a $10.5M target (89.5%). Pipeline coverage is 2.6x with $27.3M in active opportunities. Key risks: CSX ($980K) stalled due to champion departure, and Evergreen Marine ($720K) stuck in legal review. Upside: Amazon Global Logistics ($2.1M) and BNSF Railway ($1.3M) are both in active negotiation. If we close Amazon and BNSF on schedule, we'll exceed target by $1.2M. Recommendation: Allocate executive resources to unstick CSX and accelerate Evergreen legal review.",
  team_quota_attainment: "Team quota attainment through March: 68% ($7.1M of $10.5M). Top performer: Midwest territory rep at 82% with ArcBest renewal and J.B. Hunt in late-stage negotiation. Underperformer: Southeast territory at 51% -- Werner Enterprises follow-up has been slow and Saia is early stage. Three reps are on track to hit quota, two need pipeline acceleration, one needs immediate coaching intervention. FedEx Freight pilot ($550K) closing by April 15 would bring the team to 73%.",
  at_risk_deals: "Five deals totaling $3.56M are at risk in Q2: (1) CSX $980K -- champion departed, budget freeze rumored, needs exec outreach; (2) Hyundai Glovis $840K -- Seoul HQ approval bottleneck, currency concerns; (3) Knight-Swift $670K -- aggressive discount request, incumbent matching; (4) Wan Hai Lines $510K -- went silent, competitor won pilot, recommend removing; (5) Hub Group $450K -- restructuring, contact reassigned. Immediate actions: Remove Wan Hai from Q2, assign exec sponsor to CSX, reframe Knight-Swift on value not price.",
  q2_strategy: "Q2 strategic priorities: (1) Close Amazon Global Logistics ($2.1M) -- this is our largest opportunity and requires sustainability certification documentation; (2) Finalize BNSF 5-year framework ($1.3M) -- counter competitor pricing with safety track record data; (3) Convert Walmart Transportation ($1.6M) from proposal to negotiation -- their incumbent is failing audits, timing is ideal; (4) Accelerate P&G global framework ($1.4M) -- recyclable product line is our differentiator; (5) De-risk forecast by resolving stalled deals within 2 weeks or moving them out. Target: $11.2M closed revenue by June 30."
};

export const WEEKLY_DATA = [
  { week: "W1 Mar", calls: 142, emails: 389, meetings: 34, proposals: 8, closed: 310000 },
  { week: "W2 Mar", calls: 156, emails: 412, meetings: 38, proposals: 11, closed: 750000 },
  { week: "W3 Mar", calls: 138, emails: 378, meetings: 31, proposals: 7, closed: 280000 },
  { week: "W4 Mar", calls: 167, emails: 445, meetings: 42, proposals: 13, closed: 940000 },
  { week: "W1 Apr", calls: 151, emails: 401, meetings: 36, proposals: 9, closed: 0 }
];

export const PIPELINE_DATA = [
  { stage: "Discovery", value: 4820000, count: 12 },
  { stage: "Qualification", value: 3460000, count: 8 },
  { stage: "Proposal Sent", value: 4940000, count: 9 },
  { stage: "Negotiation", value: 7940000, count: 7 },
  { stage: "Closed Won", value: 2280000, count: 4 }
];

export const CHAT_SUGGESTIONS = [
  "Revenue forecast",
  "Team quota attainment",
  "At-risk deals",
  "Q2 strategy"
];

export const FUNNEL_DATA = [
  { stage: "Leads Generated", value: 187 },
  { stage: "Qualified", value: 94 },
  { stage: "Proposal Sent", value: 52 },
  { stage: "Negotiation", value: 28 },
  { stage: "Closed Won", value: 14 }
];

export const TOP_TEMPLATES = [
  { name: "Load Securement ROI Calculator", uses: 84, conversion: "34%" },
  { name: "Cargo Damage Cost Analysis", uses: 72, conversion: "29%" },
  { name: "Dunnage Airbag Product Comparison", uses: 67, conversion: "26%" },
  { name: "Safety Compliance Checklist", uses: 61, conversion: "31%" },
  { name: "Multi-Modal Securement Guide", uses: 55, conversion: "22%" }
];
